### PR TITLE
Add Rust Overlay to flake to allow for latest stable Rust toolchain

### PR DESCRIPTION
**Pull request by chanman3388**
Found this as bitstream-io v2.4.2 needs rustc 1.79 or newer.

### CODE REVIEW

**Comment by matt1432** [comment]
This didn't work for me. I made my own PR here: https://github.com/danyspin97/wpaperd/pull/84

**Comment by chanman3388** [comment]
> This didn't work for me. I made my own PR here: #84

I'm unsure why it works for me:
```
$ rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09) (built from a source tarball)

$ nix develop
warning: Git tree '/home/chris/projects/wpaperd' is dirty

$ rustc --version
rustc 1.79.0 (129f3b996 2024-06-10)
```

**Comment by chanman3388** [comment]
> This didn't work for me. I made my own PR here: #84

I _think_ I've fixed.

**Comment by matt1432** [comment]
Yes that fixes it. I'll close my PR in favor of yours!

**Comment by danyspin97** [comment]
Thank you for the PR and sorry for the delay!

**Pull request merged**
