### PR TITLE
Add mutex to prevent borrowing error

### LINKED ISSUE #10: Crash when connected to new monitor
`wpaperd` crashes when new monitor connects.

### PR DESCRIPTION
**Pull request by 1995parham**
Resolve #10 

I have added mutex to prevent multiple mutable reference at the same time, and it works.

### CODE REVIEW

**Comment by danyspin97** [comment]
The idea of using a mutex is corret, we just need to wrap surfaces with a mutex instead of `RefCell` in https://github.com/danyspin97/wpaperd/blob/main/src/main.rs#L84.

**Comment by 1995parham** [comment]
Sure, I will change it to use mutex on surfaces.

**Comment by 1995parham** [comment]
I tried to use Mutex instead of `RefCell`, I hope it is okay :see_no_evil:

**Comment by danyspin97** [comment]
Yea, it is okay. Thank you for your PR! 😄

**Pull request merged**
