### PR TITLE
Rustfmt on surface.rs and wallpaper_info.rs

### PR DESCRIPTION
**Pull request by anoldguy**
Missed step in my last PR. 😅

### CODE REVIEW

**Comment by Rolv-Apneseth** [comment]
Oh I rebased onto the main branch already, currently just figuring some things out with the code but this shouldn't be necessary, I've formatted everything.

**Comment by anoldguy** [comment]
> Oh I rebased onto the main branch already, currently just figuring some things out with the code but this shouldn't be necessary, I've formatted everything.

Ahh, I wasn't sure you were proceeding with that, since you closed your PR.

**Comment by Rolv-Apneseth** [comment]
Apologies, the PR was closed automatically since I had to sync my main branch to this repo and move my changes to a different branch, I'll reopen when I fix some issues with how it's working

**Comment by danyspin97** [comment]
Thank you for your PR @anoldguy! Let's wait a bit and see if we can merge #38 instead, since it contains the same fixes. By seeing the commits there, I think it would be easier for @Rolv-Apneseth than rebasing again.

**Comment by danyspin97** [comment]
Thank you again @anoldguy for the MR, I am going to close it since #38 has been merged.

**Pull request closed without merging**
