### PR TITLE
feat: Added Nix Flake support

### PR DESCRIPTION
**Pull request by Narice**
Added Nix Flake support to this repository so that anyone using Nix can use this project.
Tested on my own system, works really well, thanks for the tool, it's awesome!

oh, also, if it's were possible to own a cachix instance, it would mean that Nix results would be cached (and so the build would be done once only).
I can take care of everything, or you can take the free instance for open source [here](https://www.cachix.org/), and I can take care of the GitHub Action setup. As you wish!

### CODE REVIEW

**Comment by danyspin97** [comment]
Hello! Thanks for the PR and sorry for the delay. Adding Nix Flake support is a great idea, I am looking forward to merge this PR.

Wpaperd has gone through a refactoring, so the nix support should be updated as well. `timer` is not being used anymore and wpaperd is using a git version of `smithay-client-toolkit`. Can you please update it?

Regarding the cachix instance, I don't know much about nix, let me have a look so that I can give you a better answer :)

**Comment by Narice** [comment]
Hi! Thank you for your message. I'll change what you brought up

**Comment by quantenzitrone** [comment]
Hi, here is the fixed `nix/default.nix`:

```nix
{
  config,
  lib,
  pkgs,
  rustPlatform,
  version,
  pkg-config,
  wayland,
  glew-egl,
  ...
}:

rustPlatform.buildRustPackage rec {
  inherit version;
  pname = "wpaperd";

  src = lib.cleanSourceWith {
    filter =
      name: type:
      let
        baseName = baseNameOf (toString name);
      in
      !(lib.hasSuffix ".nix" baseName);
    src = lib.cleanSource ../.;
  };

  cargoLock = {
    lockFile = ../Cargo.lock;
  };

  nativeBuildInputs = [ pkg-config ];

  buildInputs = [
    wayland
    glew-egl
  ];

  meta = with lib; {
    homepage = "https://github.com/danyspin97/wpaperd";
    description = "Wallpaper daemon for Wayland";
    license = licenses.gpl3Plus;
    platforms = platforms.linux;
    mainProgram = "wpaperd";
  };
}
```

I did this because I wanted to try out the unreleased wpaperd features.

I'd also advise adding `result` to `.gitignore` so nix evaluation results are ignored.

**Comment by yunfachi** [comment]
> Hi, here is the fixed `nix/default.nix`:
Unused lambda pattern: config

**Comment by tbaumann** [comment]
Perhaps drop a section in the Readme about flake usage.

**Comment by danyspin97** [comment]
Since this PR hasn't been updated, I am going to close it in favor of #52.

**Pull request closed without merging**
