### PR TITLE
Add shell expansion

### LINKED ISSUE #9: Replace home in the path
It would be great if we can have the following path:

```
$HOME/Pictures/background
```

or

```
~/Pictures/background
```

### PR DESCRIPTION
**Pull request by 1995parham**
Closes #9 

Based on [shellexpand](https://docs.rs/shellexpand/2.1.0/shellexpand/) crate.

### CODE REVIEW

**Comment by 1995parham** [comment]
@danyspin97 Thanks for this awesome tool. I am new to rust, so if there is any issue with this PR I will be happy to fix.

**Comment by danyspin97** [comment]
Hi Parham and thank you for the contribution. I have looked up for shellexpand and it's not maintained anymore, so I'd prefer to avoid using it. I'd say that supporting the tilde expansion should be enough and we can manually expand it.

**Comment by 1995parham** [comment]
Sure @danyspin97 you are right. I will change it to manually expand `~`.

**Comment by 1995parham** [comment]
I used `dirs` package, which is a dependency of `xdg` package, for finding the home and replacing the tilde with it. We can have more replace too if you want.

**Comment by 1995parham** [comment]
Sorry for bothering you, what do you think about this PR? Replacing `~` is enough?

**Comment by danyspin97** [comment]
> Replacing ~ is enough?

Yea, I think it is enough. However, there are still a couple of issues that I have highlighted in the comments. Can you please have a look? Also, this function should also be applied to clap `--config-` parameter, but I'll implement this after this PR gets merged.

**Comment by 1995parham** [comment]
@danyspin97 Thanks. I can't see those comments, can you please mention me there? I have only one comment about not using the `shellexpand` package, which I fixed.

**Comment by danyspin97** [comment]
Can you see them if you go to "Files changed" tab in this PR?

**Comment by danyspin97** [comment]
Sorry, I hadn't actually sent the review. Fixed now 😄

**Pull request merged**
